# Site settings
name: Strategic Networking and Communications Laboratory
nickname: SNAClab
email: cywang@citi.sinica.edu.tw
author: Chih-Yu Wang

keywords: game theory, networking, communication, data, information, citi, sinica
description: > # this means to ignore newlines until "baseurl:"
  Witty description here.

baseurl:
url: https://snaclab.citi.sinica.edu.tw

header: yes
header_sm: images/banner-small.jpg
header_med: images/banner-med.jpg
header_large: images/banner-large.jpg
header_xl: images/banner-xl.jpg

fb_img: images/site_fb_img.png
# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

# Compress our Css
#sass:
#    style: :compressed

permalink: /news/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: UA-68174559-1
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user:
twitter_card: false
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
